// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrgros/keycloak-events-adapter/internal (interfaces: EventProvider)
//
// Generated by this command:
//
//	go generate ./internal/...
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	internal "keycloak-events-adapter/internal"
)

// MockEventProvider is a mock of EventProvider interface.
type MockEventProvider struct {
	ctrl     *gomock.Controller
	recorder *MockEventProviderMockRecorder
	isgomock struct{}
}

// MockEventProviderMockRecorder is the mock recorder for MockEventProvider.
type MockEventProviderMockRecorder struct {
	mock *MockEventProvider
}

// NewMockEventProvider creates a new mock instance.
func NewMockEventProvider(ctrl *gomock.Controller) *MockEventProvider {
	mock := &MockEventProvider{ctrl: ctrl}
	mock.recorder = &MockEventProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventProvider) EXPECT() *MockEventProviderMockRecorder {
	return m.recorder
}

// PushAdmin mocks base method.
func (m *MockEventProvider) PushAdmin(event *internal.AdminEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PushAdmin", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PushAdmin indicates an expected call of PushAdmin.
func (mr *MockEventProviderMockRecorder) PushAdmin(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PushAdmin", reflect.TypeOf((*MockEventProvider)(nil).PushAdmin), event)
}

// Push mocks base method.
func (m *MockEventProvider) Push(event *internal.Event) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockEventProviderMockRecorder) Push(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockEventProvider)(nil).Push), event)
}

// Read mocks base method.
func (m *MockEventProvider) Read(ctx context.Context, numWorkers int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Read", ctx, numWorkers)
}

// Read indicates an expected call of Read.
func (mr *MockEventProviderMockRecorder) Read(ctx any, numWorkers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Read", reflect.TypeOf((*MockEventProvider)(nil).Read), ctx, numWorkers)
}
