// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mrgros/keycloak-events-adapter/internal (interfaces: EventKeeper)
//
// Generated by this command:
//
//	mockgen -destination=mock/event.go -package=mock -source=event.go EventKeeper
//

// Package mock is a generated GoMock package.
package mock

import (
	"context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEventKeeper is a mock of EventKeeper interface.
type MockEventKeeper[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockEventKeeperMockRecorder[T]
	isgomock struct{}
}

// MockEventKeeperMockRecorder is the mock recorder for MockEventKeeper.
type MockEventKeeperMockRecorder[T any] struct {
	mock *MockEventKeeper[T]
}

// NewMockEventKeeper creates a new mock instance.
func NewMockEventKeeper[T any](ctrl *gomock.Controller) *MockEventKeeper[T] {
	mock := &MockEventKeeper[T]{ctrl: ctrl}
	mock.recorder = &MockEventKeeperMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEventKeeper[T]) EXPECT() *MockEventKeeperMockRecorder[T] {
	return m.recorder
}

// Push mocks base method.
func (m *MockEventKeeper[T]) Push(event *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", event)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockEventKeeperMockRecorder[T]) Push(event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockEventKeeper[T])(nil).Push), event)
}

// Process mocks base method.
func (m *MockEventKeeper[T]) Process(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Process", ctx)
}

// Process indicates an expected call of Process.
func (mr *MockEventKeeperMockRecorder[T]) Process(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Process", reflect.TypeOf((*MockEventKeeper[T])(nil).Process), ctx)
}
