// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/tarantool/go-tarantool/queue (interfaces: Queue)
//
// Generated by this command:
//
//	mockgen -destination=mock/queue.go -package=mock github.com/tarantool/go-tarantool/queue Queue
//

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"
	time "time"

	uuid "github.com/google/uuid"
	queue "github.com/tarantool/go-tarantool/queue"
	gomock "go.uber.org/mock/gomock"
)

// MockQueue is a mock of Queue interface.
type MockQueue struct {
	ctrl     *gomock.Controller
	recorder *MockQueueMockRecorder
	isgomock struct{}
}

// MockQueueMockRecorder is the mock recorder for MockQueue.
type MockQueueMockRecorder struct {
	mock *MockQueue
}

// NewMockQueue creates a new mock instance.
func NewMockQueue(ctrl *gomock.Controller) *MockQueue {
	mock := &MockQueue{ctrl: ctrl}
	mock.recorder = &MockQueueMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueue) EXPECT() *MockQueueMockRecorder {
	return m.recorder
}

// Cfg mocks base method.
func (m *MockQueue) Cfg(opts queue.CfgOpts) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cfg", opts)
	ret0, _ := ret[0].(error)
	return ret0
}

// Cfg indicates an expected call of Cfg.
func (mr *MockQueueMockRecorder) Cfg(opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cfg", reflect.TypeOf((*MockQueue)(nil).Cfg), opts)
}

// Create mocks base method.
func (m *MockQueue) Create(cfg queue.Cfg) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockQueueMockRecorder) Create(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQueue)(nil).Create), cfg)
}

// Delete mocks base method.
func (m *MockQueue) Delete(taskId uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", taskId)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQueueMockRecorder) Delete(taskId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQueue)(nil).Delete), taskId)
}

// Drop mocks base method.
func (m *MockQueue) Drop() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Drop")
	ret0, _ := ret[0].(error)
	return ret0
}

// Drop indicates an expected call of Drop.
func (mr *MockQueueMockRecorder) Drop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drop", reflect.TypeOf((*MockQueue)(nil).Drop))
}

// Exists mocks base method.
func (m *MockQueue) Exists() (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists")
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockQueueMockRecorder) Exists() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockQueue)(nil).Exists))
}

// Identify mocks base method.
func (m *MockQueue) Identify(u *uuid.UUID) (uuid.UUID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Identify", u)
	ret0, _ := ret[0].(uuid.UUID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Identify indicates an expected call of Identify.
func (mr *MockQueueMockRecorder) Identify(u any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Identify", reflect.TypeOf((*MockQueue)(nil).Identify), u)
}

// Kick mocks base method.
func (m *MockQueue) Kick(count uint64) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Kick", count)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Kick indicates an expected call of Kick.
func (mr *MockQueueMockRecorder) Kick(count any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Kick", reflect.TypeOf((*MockQueue)(nil).Kick), count)
}

// Peek mocks base method.
func (m *MockQueue) Peek(taskId uint64) (*queue.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Peek", taskId)
	ret0, _ := ret[0].(*queue.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Peek indicates an expected call of Peek.
func (mr *MockQueueMockRecorder) Peek(taskId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Peek", reflect.TypeOf((*MockQueue)(nil).Peek), taskId)
}

// Put mocks base method.
func (m *MockQueue) Put(data any) (*queue.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", data)
	ret0, _ := ret[0].(*queue.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockQueueMockRecorder) Put(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockQueue)(nil).Put), data)
}

// PutWithOpts mocks base method.
func (m *MockQueue) PutWithOpts(data any, cfg queue.Opts) (*queue.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PutWithOpts", data, cfg)
	ret0, _ := ret[0].(*queue.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PutWithOpts indicates an expected call of PutWithOpts.
func (mr *MockQueueMockRecorder) PutWithOpts(data, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PutWithOpts", reflect.TypeOf((*MockQueue)(nil).PutWithOpts), data, cfg)
}

// ReleaseAll mocks base method.
func (m *MockQueue) ReleaseAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReleaseAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// ReleaseAll indicates an expected call of ReleaseAll.
func (mr *MockQueueMockRecorder) ReleaseAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReleaseAll", reflect.TypeOf((*MockQueue)(nil).ReleaseAll))
}

// State mocks base method.
func (m *MockQueue) State() (queue.State, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "State")
	ret0, _ := ret[0].(queue.State)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// State indicates an expected call of State.
func (mr *MockQueueMockRecorder) State() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "State", reflect.TypeOf((*MockQueue)(nil).State))
}

// Statistic mocks base method.
func (m *MockQueue) Statistic() (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Statistic")
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Statistic indicates an expected call of Statistic.
func (mr *MockQueueMockRecorder) Statistic() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statistic", reflect.TypeOf((*MockQueue)(nil).Statistic))
}

// Take mocks base method.
func (m *MockQueue) Take() (*queue.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Take")
	ret0, _ := ret[0].(*queue.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Take indicates an expected call of Take.
func (mr *MockQueueMockRecorder) Take() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Take", reflect.TypeOf((*MockQueue)(nil).Take))
}

// TakeTimeout mocks base method.
func (m *MockQueue) TakeTimeout(timeout time.Duration) (*queue.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TakeTimeout", timeout)
	ret0, _ := ret[0].(*queue.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TakeTimeout indicates an expected call of TakeTimeout.
func (mr *MockQueueMockRecorder) TakeTimeout(timeout any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeTimeout", reflect.TypeOf((*MockQueue)(nil).TakeTimeout), timeout)
}

// TakeTyped mocks base method.
func (m *MockQueue) TakeTyped(arg0 any) (*queue.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TakeTyped", arg0)
	ret0, _ := ret[0].(*queue.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TakeTyped indicates an expected call of TakeTyped.
func (mr *MockQueueMockRecorder) TakeTyped(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeTyped", reflect.TypeOf((*MockQueue)(nil).TakeTyped), arg0)
}

// TakeTypedTimeout mocks base method.
func (m *MockQueue) TakeTypedTimeout(timeout time.Duration, result any) (*queue.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TakeTypedTimeout", timeout, result)
	ret0, _ := ret[0].(*queue.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TakeTypedTimeout indicates an expected call of TakeTypedTimeout.
func (mr *MockQueueMockRecorder) TakeTypedTimeout(timeout, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TakeTypedTimeout", reflect.TypeOf((*MockQueue)(nil).TakeTypedTimeout), timeout, result)
}
